
xpath_mapping = {
    "live": "https://www.voltactivedata.com",
    "dev": "https://voltDEV:ww9E1ShSNAGLD@M7w@dev.voltactivedata.com",
    "stg": "https://voltSTG:oI5L!YKmQ@1gOvqQ@stg.voltactivedata.com",
    "try-volt": "//*[@id=\"post-18176\"]/div/div/div[1]/div/div/div/div/div/div/div/div[4]/a",
    "try-volt-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[1]/div/div/div/div/div/div/div/div[4]/a",
    "partners": "//*[@id=\"post-18176\"]/div/div/div[1]/div/div/div/div/div/div/div/div[5]/a",
    "partners-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[1]/div/div/div/div/div/div/div/div[5]/a",
    "no-compromises": "//*[@id=\"post-18176\"]/div/div/div[5]/div/div/div/div[4]/div/div/div/div[3]/a",
    "no-compromises-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[5]/div/div/div/div[4]/div/div/div/div[3]/a",
    "real-time-data-processing": "//*[@id=\"post-18176\"]/div/div/div[9]/div/div/div/div[3]/div[1]/div/div/div[3]/a",
    "real-time-data-processing-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[11]/div/div/div/div[3]/div[1]/div/div/div[3]/a",
    "capabilities_1": "//*[@id=\"post-18176\"]/div/div/div[9]/div/div/div/div[3]/div[2]/div/div/div[3]/a",
    "capabilities_1-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/a",
    "cloud-native": "//*[@id=\"post-18176\"]/div/div/div[9]/div/div/div/div[5]/div[1]/div/div/div[3]/a",
    "cloud-native-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[11]/div/div/div/div[5]/div[1]/div/div/div[3]/a",
    "high-availability": "//*[@id=\"post-18176\"]/div/div/div[9]/div/div/div/div[5]/div[2]/div/div/div[3]/a",
    "high-availability-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[11]/div/div/div/div[5]/div[2]/div/div/div[3]/a",
    "geo-replication": "//*[@id=\"post-18176\"]/div/div/div[9]/div/div/div/div[5]/div[3]/div/div/div[3]/a",
    "geo-replication-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[11]/div/div/div/div[5]/div[3]/div/div/div[3]/a",
    "capabilities_2": "//*[@id=\"post-18176\"]/div/div/div[10]/div/div/div/div[3]/a",
    "capabilities_2-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/a",
    "iot-at-the-edge": "//*[@id=\"resources-list\"]/div[1]/div/div/div[2]/a",
    "iot-at-the-edge-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[14]/div/div/div/div[3]/div/div[2]/div/div/div[2]/a",
    "ai-on-the-edge-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[1]/div/div/div[2]/a",
    "streaming-data-platforms": "//*[@id=\"resources-list\"]/div[2]/div/div/div[2]/a",
    "streaming-data-platforms-live": "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[2]/div/div/div[2]/a",
    "intersection-of-edge-iot": "//*[@id=\"resources-list\"]/div[3]/div/div/div[2]/a",
    "capabilities_3": "//*[@id=\"text-4\"]/div/div/div/div[1]/div/div/div/div/div/div/div/div[2]/a",
    "capabilities_3-live": "/html/body/div[1]/div[4]/div/section/div/div/div/div[1]/div/div/div/div/div/div/div/div[2]/a",
    "why-volt": "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[1]/a",
    "no-compromises-menu" : "//*[@id=\"menu-item-22563\"]/a",
    "learn-more" : "//*[@id=\"post-22559\"]/div/div/div[7]/div/div/div/div[2]/div[2]/div/div/div[2]/a",
    "real-time" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[4]/div/div[1]/div/div/div[2]/a",
    "streaming-data" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[4]/div/div[2]/div/div/div[2]/a",
    "avoid-it" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[4]/div/div[3]/div/div/div[2]/a",
    "volt-for-5g" : "//*[@id=\"menu-item-20627\"]/a",
    "volt-for-5g-live" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[1]/ul/li[3]/a",
    "learn-more_1" : "//*[@id=\"post-20300\"]/div/div/div[7]/div/div/div/div[2]/div[1]/div/div/div[2]/a",
    "learn-more_2" : "//*[@id=\"post-20300\"]/div/div/div[9]/div/div/div/div[2]/div[2]/div/div/div[2]/a",
    "learn-more_3" : "//*[@id=\"post-20300\"]/div/div/div[11]/div/div/div/div[2]/div[1]/div/div/div[2]/a",
    "learn-more_4" : "//*[@id=\"post-20300\"]/div/div/div[13]/div/div/div/div[2]/div[2]/div/div/div[2]/a",
    "try-volt_2" : "//*[@id=\"post-20300\"]/div/div/div[25]/div/div/div/div[3]/a",
    "5g-policy" : "//*[@id=\"resources-list\"]/div[1]/div/div/div[2]/a",
    "telcos" : "//*[@id=\"resources-list\"]/div[2]/div/div/div[2]/a",
    "capabilites_4" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[1]/ul/li[3]/a",
    "capabilites_4-live" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[1]/ul/li[4]/a",
    "top-10-capabilites" : "//*[@id=\"resources-list\"]/div[1]/div/div/div[2]/a",
    "top-10-capabilites-live" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[21]/div/div/div/div/div/div[1]/div/div/div[2]/a",
    "avoid-it_2" : "//*[@id=\"resources-list\"]/div[2]/div/div/div[2]/a",
    "avoid-it_2-live" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[21]/div/div/div/div/div/div[2]/div/div/div[2]/a",
    "monitize_5g" : "//*[@id=\"resources-list\"]/div[3]/div/div/div[2]/a",
    "monitize_5g-live" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[21]/div/div/div/div/div/div[3]/div/div/div[2]/a",
    "use_cases" : "//*[@id=\"menu-item-22593\"]/a",
    "geo_replication" : "//*[@id=\"menu-item-22590\"]/a",
    "learn-more_5" : "//*[@id=\"post-19777\"]/div/div/div[1]/div/div/div/div/div[1]/div/div/div[2]/a",
    "5g-monetization" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[3]/div/div[1]/div/div/div[2]/a",
    "avoid-it_3" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[3]/div/div[2]/div/div/div[2]/a",
    "new_sql" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[3]/div/div[3]/div/div/div[2]/a",
    "high_availability" : "//*[@id=\"menu-item-20968\"]/a",
    "telco_provider" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[5]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/a",
    "fast_data_apps" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[7]/div/div/div/div[2]/div[1]/div/div/div[2]/div/div/div/div/div[2]/a",
    "top-10-capabilites_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div/div/div/div/div[1]/div/div/div[2]/a",
    "avoid-it_4" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div/div/div/div/div[2]/div/div/div[2]/a",
    "ai_ml" : "//*[@id=\"menu-item-22587\"]/a",
    "16_faqs" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[7]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div/a",
    "decisioning" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div[1]/div/div/div[2]/a",
    "fast_data_apps_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div[3]/div/div/div[2]/a",
    "oem" : "//*[@id=\"menu-item-22667\"]/a",
    "framework" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[7]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/a",
    "decisioning_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div[1]/div/div/div[2]/a",
    "top-10-capabilites_5" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div[2]/div/div/div[2]/a",
    "fast_data_apps_3" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div[2]/div/div/div[2]/a",
    "avoid-it_5" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div[3]/div/div/div[2]/a",
    "real_time_data" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[1]/ul/li[2]/a",
    "it-to-the-next-level-live" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[4]/div/div/div/div/div/div[1]/div/div/div[2]/a",
    "to-meet-Market-needs-live" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[4]/div/div/div/div/div/div[2]/div/div/div[2]/a",
    "data-platforms-live" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[4]/div/div/div/div/div/div[3]/div/div/div[2]/a",
    "real_time_decisioning": "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[2]/ul/li[1]/ul/li[5]/a",
    "mediation_for_telcos" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div/div/div/div/div[1]/div/div/div[2]/a",
    "real_time_personalization" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div/div/div/div/div[2]/div/div/div[2]/a",
    "cloud" : "//*[@id=\"menu-item-21024\"]/a",
    "microservices" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[7]/div/div/div/div[2]/div[1]/div/div/div[2]/div/div/div/div/div/a",
    "tech_stacks" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div/div/div/div/div[1]/div/div/div[2]/a",
    "decisioning_3" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div/div/div/div/div[2]/div/div/div[2]/a",
    "avoid-it_6" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[4]/div/div/div/div/div/div[3]/div/div/div[2]/a",
    "edge" : "//*[@id=\"menu-item-20886\"]/a",
    "edge_computing" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[7]/div/div/div/div[2]/div[1]/div/div/div[2]/div/div/div/div/div[2]/a",
    "rcr_weireless" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div[1]/div/div/div[2]/a",
    "avoid-it_7" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div[2]/div/div/div[2]/a",
    "vanilla_plus" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div[3]/div/div/div[2]/a",
    "kafka" : "//*[@id=\"menu-item-23050\"]/a",
    "streaming_data" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[7]/div/div/div/div[2]/div[1]/div/div/div[2]/div/div/div/div/div/a",
    "architects" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div/div/div/div/div[1]/div/div/div[2]/a",
    "advantage_streaming" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div[2]/a",
    "top-10-capabilites_3" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div/div/div/div/div[3]/div/div/div[2]/a",
    "billing_mediation" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[2]/ul/li[3]/ul/li[1]/a",
    "telco_mediation" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/a",
    "data_platform" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[1]/div/div/div[2]/a",
    "edge_iot" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[2]/div/div/div[2]/a",
    "kafka_challange" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[3]/div/div/div[2]/a",
    "bss" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[2]/ul/li[3]/ul/li[2]/a",
    "bss_framework" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[5]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/a",
    "bss_solution" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[2]/div[1]/div/div/div[2]/div/div/div/div/div[2]/a",
    "data_platform_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[1]/div/div/div[2]/a",
    "edge_iot_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[2]/div/div/div[2]/a",
    "kafka_challange_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[3]/div/div[3]/div/div/div[2]/a",
    "fantasy_sports" : "//*[@id=\"menu-item-22963\"]/a",
    "sports_apps" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[2]/div[1]/div/div/div[2]/div/div/div/div/div/a",
    "decisioning_4" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[4]/div/div[1]/div/div/div[2]/a",
    "top-10-capabilites_4" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[4]/div/div[2]/div/div/div[2]/a",
    "fast_data_apps_4" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[4]/div/div[3]/div/div/div[2]/a",
    "fraud_prevention" : "//*[@id=\"menu-item-18231\"]/a",
    "litsen_to_podcast" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[1]/div/div/div/div/div[1]/div/div/div[2]/a",
    "sakura" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[5]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/a",
    "age_of_5g" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[9]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/a",
    "growth_engine" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div[1]/div/div/div[2]/a",
    "avoid-it_8" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div[2]/div/div/div[2]/a",
    "new_sql_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div[3]/div/div/div[2]/a",
    "hyper_personalization" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[2]/ul/li[3]/ul/li[5]/a",
    "flytxt_case_study" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[5]/div/div/div/div[2]/div[2]/div/div/div[2]/div/div/div/div/div[2]/a",
    "advantage_streaming_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[13]/div/div/div/div[4]/div/div[1]/div/div/div[2]/a",
    "fast_data_apps_5" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[13]/div/div/div/div[4]/div/div[2]/div/div/div[2]/a",
    "avoid-it_9" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[13]/div/div/div/div[4]/div/div[3]/div/div/div[2]/a",
    "iot" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[2]/ul/li[3]/ul/li[6]/a",
    "architects_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div/div/div/div/div[1]/div/div/div[2]/a",
    "advantage_streaming_3" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div/div/div/div/div[2]/div/div/div[2]/a",
    "top-10-capabilites_6" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[11]/div/div/div/div[3]/div/div/div/div/div/div[3]/div/div/div[2]/a",
    "resources" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[3]/a",
    "resources_library" : "//*[@id=\"menu-item-18012\"]/a",
    "blog" : "//*[@id=\"menu-item-16565\"]/a",
    "partner_program" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[3]/ul/li[3]/a",
    "top-10-capabilites_7" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[5]/div/div/div/div[2]/div[2]/div/div/div[1]/div/div/div/div/div[2]/a",
    "decisioning_5" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[4]/div/div[1]/div/div/div[2]/a",
    "advantage_streaming_4" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[4]/div/div[2]/div/div/div[2]/a",
    "avoid-it_10" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[13]/div/div/div/div[4]/div/div[3]/div/div/div[2]/a",
    "webinar" : "//*[@id=\"menu-item-20696\"]/a",
    "register_now" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[4]/div/div/div/div[2]/a",
    "view_now_1" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[6]/div/div/div/div[2]/a",
    "view_now_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[7]/div/div/div/div[2]/a",
    "view_now_3" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[8]/div/div/div/div[2]/a",
    "support" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[3]/ul/li[5]/ul/li[1]/a",
    "professional_services" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[3]/ul/li[5]/ul/li[2]/a",
    "documentation" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[3]/ul/li[5]/ul/li[3]/a",
    "company" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[4]/a",
    "about" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[4]/ul/li[1]/a",
    "careers" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[4]/ul/li[2]/a",
    "linkedin_page_jobs" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/section/div[6]/div/div/div/div[2]/div/h4/span/a",
    "linkedin_page_jobs-live" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[6]/div/div/div/div[2]/div/h4/span/a",
    "linkedin_page_jobs_2" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div[4]/div/div/div/div[2]/div/h2/span/a",
    "news" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[4]/ul/li[3]/a",
    "press_release" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[4]/ul/li[4]/a",
    "telecom_certificate" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div/div/div/div/div[4]/div/div/div/div[1]/div[1]/div[2]/div/div/div/div[2]/h3/a",
    "i2i_systems" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div/div/div/div/div[4]/div/div/div/div[2]/div[1]/div[2]/div/div/div/div[2]/h3/a",
    "explosive_growth" : "/html/body/div[1]/div[3]/div/div/div/div/main/article/div/div/div/div/div/div/div[4]/div/div/div/div[4]/div[1]/div[2]/div/div/div/div[2]/h3/a",
    "team" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[4]/ul/li[5]/a",
    "contact" : "/html/body/div[1]/header/div/div/div[1]/div/div[2]/nav/div/ul/li[4]/ul/li[6]/a",
    "privacy_statment" : "/html/body/div[1]/footer/div[2]/div/div/a[1]",
    "licennse_agreement" : "/html/body/div[1]/footer/div[2]/div/div/a[2]",
    "contributor_agreement" : "/html/body/div[1]/footer/div[2]/div/div/a[3]",
    "sitemap" : "/html/body/div[1]/footer/div[2]/div/div/a[4]",
    "contact_us" : "/html/body/div[1]/footer/div[2]/div/div/a[5]",
    "twitter" : "/html/body/div[1]/footer/div[1]/div/div[1]/div[2]/section[1]/div/div/a[1]",
    "linked_in" : "/html/body/div[1]/footer/div[1]/div/div[1]/div[2]/section[1]/div/div/a[2]",
    "Type" : "/html/body/div[1]/div[3]/div/div/div/div/main/div/div[2]/form/div[1]/div",
    "Type UL" : "/html/body/div[1]/div[3]/div/div/div/div/main/div/div[2]/form/div[1]/div/ul",
    "resource_list_element" : "/html/body/div[1]/div[3]/div/div/div/div/main/div/div[3]",
    "Topic" : "/html/body/div[1]/div[3]/div/div/div/div/main/div/div[2]/form/div[2]/div",
    "Topic UL" : "/html/body/div[1]/div[3]/div/div/div/div/main/div/div[2]/form/div[2]/div/ul",
    "fraud_prevention_category" : "/html/body/div[1]/div[3]/div/div/div/aside/div/section[2]/div/ul/li[3]/a",
    "fraud_prevention_category-live" : "/html/body/div[1]/div[3]/div/div/div/aside/div/section[2]/div/ul/li[4]/a",
    "category_tag" : "/html/body/div[1]/div[2]/div/div/h1/span",
    "category_name" : "FRAUD PREVENTION",
    "Resource Title" : "TM Forum Report – Enterprise 5G",
    "search bar" : "/html/body/div[1]/div[3]/div/div/div/div/main/div/div[2]/form/div[3]/input",
    "accept_cookie" : "/html/body/div[7]/div[2]/div/div[1]/div/div[2]/div/button[3]",
}

url_mapping = {
    "try-volt": "https://www.voltactivedata.com/try-volt/",
    "partners": "https://www.voltactivedata.com/partners/",
    "no-compromises": "https://www.voltactivedata.com/no-compromises/",
    "real-time-data-processing": "https://www.voltactivedata.com/real-time-data-processing/",
    "capabilities": "https://www.voltactivedata.com/capabilities/",
    "capabilities_2": "https://dev.voltactivedata.com/capabilities/",
    "cloud-native": "https://www.voltactivedata.com/use-cases/cloud-native/",
    "high-availability": "https://www.voltactivedata.com/use-cases/high-availability/",
    "geo-replication": "https://www.voltactivedata.com/use-cases/geo-replication/",
    "iot-at-the-edge": "https://dev.voltactivedata.com/resource/tm-forum-report-iot-at-the-edge/",
    "ai-on-the-edge-live": "https://www.voltactivedata.com/resource/tmforum-report-telco-revenue-growth-taking-it-to-the-next-level/",
    "streaming-data-platforms": "https://dev.voltactivedata.com/resource/guide-to-streaming-data-platforms/",
    "intersection-of-edge-iot": "https://dev.voltactivedata.com/resource/stl-partners-report-revenue-opportunities-at-the-intersection-of-edge-iot/",
    "no-compromises-menu": "https://dev.voltactivedata.com/no-compromises/",
    "learn-more" : "https://www.voltactivedata.com/use-cases/edge-optimized-architecture/",
    "real-time" : "https://dev.voltactivedata.com/resource/six-use-cases-of-real-time-decisioning/",
    "streaming-data" : "https://dev.voltactivedata.com/press_release/volt-active-data-launches-new-product-for-capitalizing-on-streaming-data/",
    "avoid-it" : "https://dev.voltactivedata.com/resource/why-your-tech-stack-is-about-to-break-and-how-to-avoid-it/",
    "volt-for-5g": "https://dev.voltactivedata.com/volt-for-5g/",
    "learn-more_1": "https://www.voltactivedata.com/use-cases/business-support-systems-bss/",
    "learn-more_2": "https://www.voltactivedata.com/resource/activen_lossless_xdcr/",
    "learn-more_3": "https://www.voltactivedata.com/resource/customer-management-infographic/",
    "learn-more_4": "https://www.voltactivedata.com/resource/revenue-assurance-business-overview/",
    "try-volt_2" : "https://www.voltactivedata.com/try-volt/",
    "5g-policy" : "https://dev.voltactivedata.com/resource/5g-policy-survey-results/",
    "telcos" : "https://dev.voltactivedata.com/resource/powering-real-time-mediation-for-telcos/",
    "top-10-capabilites" : "https://dev.voltactivedata.com/resource/voltdb-top-10-capabilities/",
    "monitize_5g" : "https://dev.voltactivedata.com/resource/stl-partners-report-monetizing-5g/",
    "geo_replication" : "https://dev.voltactivedata.com/use-cases/geo-replication/",
    "learn-more_5" : "https://www.voltactivedata.com/resource/activen_lossless_xdcr/",
    "5g-monetization" : "https://dev.voltactivedata.com/resource/a-quick-guide-to-5g-monetization/",
    "new_sql" : "https://dev.voltactivedata.com/resource/sql-vs-nosql-vs-newsql/",
    "high_availability" : "https://dev.voltactivedata.com/use-cases/high-availability/",
    "telco_provider" : "https://dev.voltactivedata.com/resource/i2i-systems-case-study/",
    "fast_data_apps" : "https://dev.voltactivedata.com/resource/technical-overview-data-platform-for-fast-data-apps/",
    "ai_ml" : "https://dev.voltactivedata.com/use-cases/monetize-artificial-intelligence-and-machine-learning/",
    "16_faqs" : "https://dev.voltactivedata.com/blog/2018/08/16-faqs-on-machine-learning-with-true-real-time-decisioning/",
    "decisioning" : "https://dev.voltactivedata.com/resource/six-use-cases-of-real-time-decisioning/",
    "oem" : "https://dev.voltactivedata.com/use-cases/oem-friendly/",
    "framework" : "https://dev.voltactivedata.com/resource/voltdb-powers-openet-bss-application-framework/",
    "real_time_data": "https://www.voltactivedata.com/real-time-data-processing/",
    "it-to-the-next-level-live": "https://www.voltactivedata.com/resource/tmforum-report-telco-revenue-growth-taking-it-to-the-next-level/",
    "to-meet-Market-needs-live": "https://www.voltactivedata.com/resource/stl-partners-report-revenue-opportunities-at-the-intersection-of-edge-iot/",
    "data-platforms-live": "https://www.voltactivedata.com/resource/guide-to-streaming-data-platforms/",
    "real_time_decisioning": "https://stg.voltactivedata.com/use-cases/real-time-business-decisions/",
    "mediation_for_telcos": "https://dev.voltactivedata.com/resource/powering-real-time-mediation-for-telcos/",
    "real_time_personalization": "https://dev.voltactivedata.com/resource/deltadna/",
    "cloud" : "https://dev.voltactivedata.com/use-cases/cloud-native/",
    "microservices" : "https://dev.voltactivedata.com/blog/2018/08/voltdb-kubernetes-the-perfect-match-for-5g-apps-microservices/",
    "tech_stacks" : "https://dev.voltactivedata.com/resource/why-5g-standards-will-lower-tco-for-tech-stacks/",
    "edge": "https://dev.voltactivedata.com/use-cases/edge-optimized-architecture/",
    "edge_computing": "https://dev.voltactivedata.com/resource/latency-and-resilience-in-edge-computing/",
    "rcr_weireless": "https://dev.voltactivedata.com/resource/whats-the-value-of-edge/",
    "vanilla_plus": "https://dev.voltactivedata.com/resource/vanillaplus-techtrends/",
    "kafka": "https://dev.voltactivedata.com/use-cases/activesd-kafka-streaming/",
    "streaming_data": "https://dev.voltactivedata.com/press_release/volt-active-data-launches-new-product-for-capitalizing-on-streaming-data/",
    "architects": "https://dev.voltactivedata.com/resource/kafka-for-solution-architects/",
    "advantage_streaming": "https://dev.voltactivedata.com/resource/how-to-take-full-advantage-of-your-streaming-data/",
    "billing_mediation": "https://dev.voltactivedata.com/use-cases/billing-mediation-systems/",
    "telco_mediation": "https://dev.voltactivedata.com/resource/why-volt-is-the-best-data-platform-for-telco-mediation/",
    "data_platform": "https://dev.voltactivedata.com/resource/guide-to-streaming-data-platforms/",
    "edge_iot": "https://dev.voltactivedata.com/resource/stl-partners-report-revenue-opportunities-at-the-intersection-of-edge-iot/",
    "kafka_challange": "https://dev.voltactivedata.com/resource/top-7-kafka-challenges/",
    "bss" : "https://dev.voltactivedata.com/use-cases/business-support-systems-bss/",
    "bss_framework" : "https://dev.voltactivedata.com/resource/voltdb-powers-openet-bss-application-framework/",
    "bss_solution" : "https://dev.voltactivedata.com/resource/bss-solution-brief/",
    "fantasy_sports": "https://dev.voltactivedata.com/use-cases/fantasy-sports/",
    "sports_apps": "https://dev.voltactivedata.com/blog/2022/12/top-4-technical-challenges-for-fantasy-sports-apps/",
    "fraud_prevention": "https://dev.voltactivedata.com/use-cases/fraud-prevention/",
    "litsen_to_podcast": "https://www.voltactivedata.com/blog/2019/02/podcast-fraud-intrusion-detection-and-other-applications-need-a-faster-database-to-keep-up-with-5g/",
    "sakura": "https://dev.voltactivedata.com/resource/sakura-internet/",
    "age_of_5g": "https://dev.voltactivedata.com/resource/5g-revenue-assurance/",
    "growth_engine": "https://dev.voltactivedata.com/resource/stl-partners-report-cios-guide-to-5g-as-a-growth-engine/",
    "hyper_personalization": "https://dev.voltactivedata.com/use-cases/hyper-personalization/",
    "flytxt_case_study": "https://dev.voltactivedata.com/resource/flytxt-case-study/",
    "iot" : "https://dev.voltactivedata.com/use-cases/enterprise-iot/",
    "resources_library": "https://dev.voltactivedata.com/resources/",
    "blog": "https://dev.voltactivedata.com/blog/",
    "partner_program" : "https://dev.voltactivedata.com/partners/",
    "webinar" : "https://dev.voltactivedata.com/events/",
    "register_now" : "https://dtw.tmforum.org/passes/",
    "view_now_1" : "https://register.gotowebinar.com/register/1832234301684395866?source=Volt",
    "view_now_2" : "https://register.gotowebinar.com/register/1832234301684395866?source=Volt",
    "view_now_3" : "https://content.rcrwireless.com/mobile_edge_forum_webinar",
    "support" : "https://dev.voltactivedata.com/company/customers/support/",
    "professional_services": "https://dev.voltactivedata.com/resource/professional-services/",
    "documentation": "https://docs.voltactivedata.com/",
    "about" : "https://dev.voltactivedata.com/company/",
    "careers": "https://dev.voltactivedata.com/company/careers/",
    "linkedin_page_jobs": "https://www.linkedin.com/company/voltactivedata",
    "news": "https://dev.voltactivedata.com/company/news/",
    "press_release": "https://dev.voltactivedata.com/company/press-releases/",
    "telecom_certificate": "https://dev.voltactivedata.com/press_release/volt-attains-dell-technologies-telecom-certification/",
    "i2i_systems": "https://dev.voltactivedata.com/press_release/i2i-systems-meets-slas-of-major-telecom-customer-with-volt/",
    "explosive_growth": "https://dev.voltactivedata.com/press_release/volt-sees-explosive-growth/",
    "team": "https://dev.voltactivedata.com/company/team/",
    "contact": "https://dev.voltactivedata.com/company/contact/",
    "privacy_statment": "https://dev.voltactivedata.com/privacy-policy/",
    "licennse_agreement": "https://dev.voltactivedata.com/license-agreement/",
    "contributor_agreement": "https://dev.voltactivedata.com/contributor-license-agreement/",
    "sitemap": "https://dev.voltactivedata.com/sitemap/",
    "twitter" : "https://twitter.com/VoltActiveData",
    "linked_in" : "https://www.linkedin.com/company/voltactivedata/",
}
